// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  datasource: {
    // Always use a file URL for Prisma config (migrations/introspection)
    // Actual runtime connection goes through the libsql adapter
    url: process.env["DATABASE_URL"] || "file:./prisma/dev.db",
  },
});
